### ISSUE TITLE
Manual sale workflow broken with sale-payment-gateway

### ISSUE THREAD

**Issue by mbehrle** [openlabs/sale-payment-gateway#42]
With sale-payment-gateway installed it seems to be no more possible to follow the usual manual sale workflow from e.g. the client. It is impossible to process a sale without defining a payment.
This gets problematic, when using e.g. standard method settings
- invoice: on order processed
- shipment: on order processed
  and it is no more possible to emit an invoice nor shipping without registered payment, because sale-payment-gateway jumps in with:

Insufficient amount remaining in payment
Amount to capture: xx.xx
Amount remaining: 0
Payments: 0

Is this a missing configuration step or indeed a regression?

**Comment by sharoonthomas** [comment]
Setting `payment_authorize_on` and `payment_capture_on` to `manual` mode should do.
The setting exist in each order. Defaults from configuration are filled in automatically.

Does this solve the issue ?

**Comment by mbehrle** [comment]
The settings are only as defaults in the configuration, but then work indeed. I will have to check, why the fields are missing for me on sale.

What do you think of moving/adding those default settings to 'Order Defaults' on Channel? This would allow for a more fine grained control and presetting via sale channel.

**Comment by sharoonthomas** [comment]
@mbehrle good idea, but would it be better on a different module ? Something like `sale_channel_payment_gateway` and then change the `default_*` methods on sale ?

**Comment by mbehrle** [comment]
@sharoonthomas It depends on your mileage, if sale_payment_gateway should be installable without sale_channel (do you have such use cases?). For me it seems very likely to use sale channels as soon as you are using gateways. Also it is easier to refactor some functionality out into new modules than to merge them. So I would avoid in the first place such micro-modules with _glue_ functionality, which tend to cause some maintenance overhead. It can be done at any point later, if it should be necessary. Just my 2¢.

**Comment by sharoonthomas** [comment]
@tarunbhardwaj thoughts ?

**Comment by tarunbhardwaj** [comment]
`sale_payment_gateway` without `sale_channel` is possible for small tryton implementations and same other way round.
IMO separate module is better option.

**Comment by mbehrle** [comment]
Solved like proposed with a custom module available at https://gitlab.com/m9s/sale_channel_payment_gateway.

Thanks and closing.
